[package]
name = "math"
version = "0.1.0"
authors = ["Ivan Burlakov <burlakovv.ivan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
transpose = "0.2.0"